# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow


class Ui_UILogin(QMainWindow):
    def setupUi(self, UILogin):
        UILogin.setObjectName("UILogin")
        UILogin.resize(320, 200)
        self.centralwidget = QtWidgets.QWidget(UILogin)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.student = QtWidgets.QWidget()
        self.student.setObjectName("student")
        self.buttonLoginStu = QtWidgets.QPushButton(self.student)
        self.buttonLoginStu.setGeometry(QtCore.QRect(110, 120, 75, 23))
        self.buttonLoginStu.setObjectName("buttonLoginStu")
        self.widget = QtWidgets.QWidget(self.student)
        self.widget.setGeometry(QtCore.QRect(50, 20, 191, 81))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.acStu = QtWidgets.QLineEdit(self.widget)
        self.acStu.setObjectName("acStu")
        self.verticalLayout_2.addWidget(self.acStu)

        self.pwdStu = QtWidgets.QLineEdit(self.widget)
        self.pwdStu.setObjectName("pwdStu")
        self.verticalLayout_2.addWidget(self.pwdStu)

        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.student, "")
        self.teacher = QtWidgets.QWidget()
        self.teacher.setObjectName("teacher")
        self.layoutWidget = QtWidgets.QWidget(self.teacher)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 20, 191, 81))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.acTea = QtWidgets.QLineEdit(self.layoutWidget)
        self.acTea.setObjectName("acTea")
        self.verticalLayout_4.addWidget(self.acTea)
        self.pwdTea = QtWidgets.QLineEdit(self.layoutWidget)
        self.pwdTea.setObjectName("pwdTea")
        self.verticalLayout_4.addWidget(self.pwdTea)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.buttonLoginTea = QtWidgets.QPushButton(self.teacher)
        self.buttonLoginTea.setGeometry(QtCore.QRect(110, 120, 75, 23))
        self.buttonLoginTea.setObjectName("buttonLoginTea")
        self.tabWidget.addTab(self.teacher, "")
        self.admin = QtWidgets.QWidget()
        self.admin.setObjectName("admin")
        self.layoutWidget_2 = QtWidgets.QWidget(self.admin)
        self.layoutWidget_2.setGeometry(QtCore.QRect(50, 20, 191, 81))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.acAdm = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.acAdm.setObjectName("acAdm")
        self.verticalLayout_6.addWidget(self.acAdm)
        self.pwdAdm = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.pwdAdm.setObjectName("pwdAdm")
        self.verticalLayout_6.addWidget(self.pwdAdm)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.buttonLoginAdm = QtWidgets.QPushButton(self.admin)
        self.buttonLoginAdm.setGeometry(QtCore.QRect(110, 120, 75, 23))
        self.buttonLoginAdm.setObjectName("buttonLoginAdm")
        self.tabWidget.addTab(self.admin, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        UILogin.setCentralWidget(self.centralwidget)

        self.retranslateUi(UILogin)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(UILogin)

    def retranslateUi(self, UILogin):
        _translate = QtCore.QCoreApplication.translate
        UILogin.setWindowTitle(_translate("UILogin", "教务选课系统-登录界面"))
        self.buttonLoginStu.setText(_translate("UILogin", "登录"))
        self.label.setText(_translate("UILogin", "账号"))
        self.label_2.setText(_translate("UILogin", "密码"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.student), _translate("UILogin", "学生"))
        self.label_3.setText(_translate("UILogin", "账号"))
        self.label_4.setText(_translate("UILogin", "密码"))
        self.buttonLoginTea.setText(_translate("UILogin", "登录"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.teacher), _translate("UILogin", "教师"))
        self.label_5.setText(_translate("UILogin", "账号"))
        self.label_6.setText(_translate("UILogin", "密码"))
        self.buttonLoginAdm.setText(_translate("UILogin", "登录"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.admin), _translate("UILogin", "管理员"))

    def __init__(self):
        super(Ui_UILogin,self).__init__()
        self.setupUi(self)



if __name__ == '__main__':
    app = QApplication(sys.argv)
    main = Ui_UILogin()
    main.show()
    sys.exit(app.exec_())