# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainStu.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(830, 620)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.mainPage = QtWidgets.QWidget()
        self.mainPage.setObjectName("mainPage")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.mainPage)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.mainInfoList = QtWidgets.QListWidget(self.mainPage)
        self.mainInfoList.setObjectName("mainInfoList")
        self.verticalLayout.addWidget(self.mainInfoList)
        self.tabWidget.addTab(self.mainPage, "")
        self.selePage = QtWidgets.QWidget()
        self.selePage.setObjectName("selePage")
        self.gridLayout = QtWidgets.QGridLayout(self.selePage)
        self.gridLayout.setObjectName("gridLayout")
        self.seleInfoTable = QtWidgets.QTableWidget(self.selePage)
        self.seleInfoTable.setObjectName("seleInfoTable")
        self.seleInfoTable.setColumnCount(6)
        self.seleInfoTable.setRowCount(24)
        item = QtWidgets.QTableWidgetItem()
        self.seleInfoTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.seleInfoTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.seleInfoTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.seleInfoTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.seleInfoTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.seleInfoTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.seleInfoTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.seleInfoTable.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.seleInfoTable.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.seleInfoTable.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.seleInfoTable.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.seleInfoTable.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.seleInfoTable.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.seleInfoTable.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.seleInfoTable.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.seleInfoTable.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.seleInfoTable.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.seleInfoTable.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.seleInfoTable.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.seleInfoTable.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.seleInfoTable.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.seleInfoTable.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.seleInfoTable.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.seleInfoTable.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.seleInfoTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.seleInfoTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.seleInfoTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.seleInfoTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.seleInfoTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.seleInfoTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.seleInfoTable.setItem(0, 0, item)
        self.seleInfoTable.horizontalHeader().setDefaultSectionSize(120)
        self.gridLayout.addWidget(self.seleInfoTable, 0, 0, 1, 1)
        self.tabWidget.addTab(self.selePage, "")
        self.quitPage = QtWidgets.QWidget()
        self.quitPage.setObjectName("quitPage")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.quitPage)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.quitInfoTable = QtWidgets.QTableWidget(self.quitPage)
        self.quitInfoTable.setObjectName("quitInfoTable")
        self.quitInfoTable.setColumnCount(6)
        self.quitInfoTable.setRowCount(24)
        item = QtWidgets.QTableWidgetItem()
        self.quitInfoTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.quitInfoTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.quitInfoTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.quitInfoTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.quitInfoTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.quitInfoTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.quitInfoTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.quitInfoTable.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.quitInfoTable.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.quitInfoTable.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.quitInfoTable.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.quitInfoTable.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.quitInfoTable.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.quitInfoTable.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.quitInfoTable.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.quitInfoTable.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.quitInfoTable.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.quitInfoTable.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.quitInfoTable.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.quitInfoTable.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.quitInfoTable.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.quitInfoTable.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.quitInfoTable.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.quitInfoTable.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.quitInfoTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.quitInfoTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.quitInfoTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.quitInfoTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.quitInfoTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.quitInfoTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.quitInfoTable.setItem(0, 0, item)
        self.quitInfoTable.horizontalHeader().setDefaultSectionSize(120)
        self.gridLayout_2.addWidget(self.quitInfoTable, 0, 0, 1, 1)
        self.tabWidget.addTab(self.quitPage, "")
        self.timeTablePage = QtWidgets.QWidget()
        self.timeTablePage.setObjectName("timeTablePage")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.timeTablePage)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.timeTable = QtWidgets.QTableWidget(self.timeTablePage)
        self.timeTable.setRowCount(12)
        self.timeTable.setColumnCount(7)
        self.timeTable.setObjectName("timeTable")
        item = QtWidgets.QTableWidgetItem()
        self.timeTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.timeTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.timeTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.timeTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.timeTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.timeTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.timeTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.timeTable.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.timeTable.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.timeTable.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.timeTable.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.timeTable.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.timeTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.timeTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.timeTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.timeTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.timeTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.timeTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.timeTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.timeTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.timeTable.setItem(0, 1, item)
        self.timeTable.horizontalHeader().setDefaultSectionSize(100)
        self.timeTable.horizontalHeader().setMinimumSectionSize(30)
        self.timeTable.verticalHeader().setDefaultSectionSize(40)
        self.gridLayout_3.addWidget(self.timeTable, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.timeTablePage)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.timeTablePage, "")
        self.examPage = QtWidgets.QWidget()
        self.examPage.setObjectName("examPage")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.examPage)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.examTable = QtWidgets.QTableWidget(self.examPage)
        self.examTable.setRowCount(12)
        self.examTable.setColumnCount(7)
        self.examTable.setObjectName("examTable")
        item = QtWidgets.QTableWidgetItem()
        self.examTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.examTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.examTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.examTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.examTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.examTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.examTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.examTable.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.examTable.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.examTable.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.examTable.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.examTable.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.examTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.examTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.examTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.examTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.examTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.examTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.examTable.setHorizontalHeaderItem(6, item)
        self.examTable.horizontalHeader().setDefaultSectionSize(100)
        self.examTable.horizontalHeader().setMinimumSectionSize(30)
        self.examTable.verticalHeader().setDefaultSectionSize(40)
        self.gridLayout_4.addWidget(self.examTable, 0, 0, 1, 1)
        self.tabWidget.addTab(self.examPage, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 830, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionLogin = QtWidgets.QAction(MainWindow)
        self.actionLogin.setObjectName("actionLogin")
        self.actionRegister = QtWidgets.QAction(MainWindow)
        self.actionRegister.setObjectName("actionRegister")
        self.menuFile.addAction(self.actionLogin)
        self.menuFile.addAction(self.actionExit)
        self.menuAbout.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "教务选课系统-学生界面"))
        self.pushButton.setText(_translate("MainWindow", "刷新"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mainPage), _translate("MainWindow", "主页"))
        item = self.seleInfoTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "01"))
        item = self.seleInfoTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "02"))
        item = self.seleInfoTable.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "03"))
        item = self.seleInfoTable.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "04"))
        item = self.seleInfoTable.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "05"))
        item = self.seleInfoTable.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "06"))
        item = self.seleInfoTable.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "07"))
        item = self.seleInfoTable.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "08"))
        item = self.seleInfoTable.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "09"))
        item = self.seleInfoTable.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        item = self.seleInfoTable.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "11"))
        item = self.seleInfoTable.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "12"))
        item = self.seleInfoTable.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "13"))
        item = self.seleInfoTable.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "14"))
        item = self.seleInfoTable.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "15"))
        item = self.seleInfoTable.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "16"))
        item = self.seleInfoTable.verticalHeaderItem(16)
        item.setText(_translate("MainWindow", "17"))
        item = self.seleInfoTable.verticalHeaderItem(17)
        item.setText(_translate("MainWindow", "18"))
        item = self.seleInfoTable.verticalHeaderItem(18)
        item.setText(_translate("MainWindow", "19"))
        item = self.seleInfoTable.verticalHeaderItem(19)
        item.setText(_translate("MainWindow", "20"))
        item = self.seleInfoTable.verticalHeaderItem(20)
        item.setText(_translate("MainWindow", "21"))
        item = self.seleInfoTable.verticalHeaderItem(21)
        item.setText(_translate("MainWindow", "22"))
        item = self.seleInfoTable.verticalHeaderItem(22)
        item.setText(_translate("MainWindow", "23"))
        item = self.seleInfoTable.verticalHeaderItem(23)
        item.setText(_translate("MainWindow", "24"))
        item = self.seleInfoTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "选修"))
        item = self.seleInfoTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "课程号"))
        item = self.seleInfoTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "新建列"))
        item = self.seleInfoTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "课程名"))
        item = self.seleInfoTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "班级名"))
        item = self.seleInfoTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "上课时间"))
        __sortingEnabled = self.seleInfoTable.isSortingEnabled()
        self.seleInfoTable.setSortingEnabled(False)
        item = self.seleInfoTable.item(0, 0)
        item.setText(_translate("MainWindow", "123"))
        self.seleInfoTable.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.selePage), _translate("MainWindow", "选课"))
        item = self.quitInfoTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "01"))
        item = self.quitInfoTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "02"))
        item = self.quitInfoTable.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "03"))
        item = self.quitInfoTable.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "04"))
        item = self.quitInfoTable.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "05"))
        item = self.quitInfoTable.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "06"))
        item = self.quitInfoTable.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "07"))
        item = self.quitInfoTable.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "08"))
        item = self.quitInfoTable.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "09"))
        item = self.quitInfoTable.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        item = self.quitInfoTable.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "11"))
        item = self.quitInfoTable.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "12"))
        item = self.quitInfoTable.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "13"))
        item = self.quitInfoTable.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "14"))
        item = self.quitInfoTable.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "15"))
        item = self.quitInfoTable.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "16"))
        item = self.quitInfoTable.verticalHeaderItem(16)
        item.setText(_translate("MainWindow", "17"))
        item = self.quitInfoTable.verticalHeaderItem(17)
        item.setText(_translate("MainWindow", "18"))
        item = self.quitInfoTable.verticalHeaderItem(18)
        item.setText(_translate("MainWindow", "19"))
        item = self.quitInfoTable.verticalHeaderItem(19)
        item.setText(_translate("MainWindow", "20"))
        item = self.quitInfoTable.verticalHeaderItem(20)
        item.setText(_translate("MainWindow", "21"))
        item = self.quitInfoTable.verticalHeaderItem(21)
        item.setText(_translate("MainWindow", "22"))
        item = self.quitInfoTable.verticalHeaderItem(22)
        item.setText(_translate("MainWindow", "23"))
        item = self.quitInfoTable.verticalHeaderItem(23)
        item.setText(_translate("MainWindow", "24"))
        item = self.quitInfoTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "退课"))
        item = self.quitInfoTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "课程号"))
        item = self.quitInfoTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "新建列"))
        item = self.quitInfoTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "课程名"))
        item = self.quitInfoTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "班级名"))
        item = self.quitInfoTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "上课时间"))
        __sortingEnabled = self.quitInfoTable.isSortingEnabled()
        self.quitInfoTable.setSortingEnabled(False)
        item = self.quitInfoTable.item(0, 0)
        item.setText(_translate("MainWindow", "123"))
        self.quitInfoTable.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.quitPage), _translate("MainWindow", "退课"))
        item = self.timeTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "8:30-9:15"))
        item = self.timeTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "9:25-10:10"))
        item = self.timeTable.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "10:30-11:15"))
        item = self.timeTable.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "11:25-12:10"))
        item = self.timeTable.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "14:00-14:45"))
        item = self.timeTable.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "14:55-15:40"))
        item = self.timeTable.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "15:50-16:35"))
        item = self.timeTable.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "16:45-17:30"))
        item = self.timeTable.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "18:30-19:15"))
        item = self.timeTable.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "19:25-20:10"))
        item = self.timeTable.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "20:20-21:05"))
        item = self.timeTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "MON"))
        item = self.timeTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "TUE"))
        item = self.timeTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "WED"))
        item = self.timeTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "THU"))
        item = self.timeTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "FRI"))
        item = self.timeTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "SAT"))
        item = self.timeTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "SUN"))
        __sortingEnabled = self.timeTable.isSortingEnabled()
        self.timeTable.setSortingEnabled(False)
        self.timeTable.setSortingEnabled(__sortingEnabled)
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.timeTablePage), _translate("MainWindow", "时间表"))
        item = self.examTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "8:30-9:15"))
        item = self.examTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "9:25-10:10"))
        item = self.examTable.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "10:30-11:15"))
        item = self.examTable.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "11:25-12:10"))
        item = self.examTable.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "14:00-14:45"))
        item = self.examTable.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "14:55-15:40"))
        item = self.examTable.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "15:50-16:35"))
        item = self.examTable.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "16:45-17:30"))
        item = self.examTable.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "18:30-19:15"))
        item = self.examTable.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "19:25-20:10"))
        item = self.examTable.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "20:20-21:05"))
        item = self.examTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "MON"))
        item = self.examTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "TUE"))
        item = self.examTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "WED"))
        item = self.examTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "THU"))
        item = self.examTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "FRI"))
        item = self.examTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "SAT"))
        item = self.examTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "SUN"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.examPage), _translate("MainWindow", "考试安排"))
        self.menuFile.setTitle(_translate("MainWindow", "操作"))
        self.menuAbout.setTitle(_translate("MainWindow", "关于"))
        self.actionExit.setText(_translate("MainWindow", "退出"))
        self.actionAbout.setText(_translate("MainWindow", "关于"))
        self.actionLogin.setText(_translate("MainWindow", "登录"))
        self.actionRegister.setText(_translate("MainWindow", "注册"))
