# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainTea.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainTeaWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(830, 620)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.mainPage = QtWidgets.QWidget()
        self.mainPage.setObjectName("mainPage")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.buttonRefresh = QtWidgets.QPushButton(self.mainPage)
        self.buttonRefresh.setObjectName("buttonRefresh")
        self.verticalLayout.addWidget(self.buttonRefresh)
        self.mainInfoList = QtWidgets.QListWidget(self.mainPage)
        self.mainInfoList.setObjectName("mainInfoList")
        self.verticalLayout.addWidget(self.mainInfoList)
        self.tabWidget.addTab(self.mainPage, "")
        self.teachInfoPage = QtWidgets.QWidget()
        self.teachInfoPage.setObjectName("teachInfoPage")
        self.gridLayout = QtWidgets.QGridLayout(self.teachInfoPage)
        self.gridLayout.setObjectName("gridLayout")
        self.teachInfoTable = QtWidgets.QTableWidget(self.teachInfoPage)
        self.teachInfoTable.setObjectName("teachInfoTable")
        self.teachInfoTable.setColumnCount(4)
        self.teachInfoTable.setRowCount(9)
        item = QtWidgets.QTableWidgetItem()
        self.teachInfoTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.teachInfoTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.teachInfoTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.teachInfoTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.teachInfoTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.teachInfoTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.teachInfoTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.teachInfoTable.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.teachInfoTable.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.teachInfoTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.teachInfoTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.teachInfoTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.teachInfoTable.setHorizontalHeaderItem(3, item)
        self.teachInfoTable.horizontalHeader().setDefaultSectionSize(190)
        self.teachInfoTable.horizontalHeader().setMinimumSectionSize(30)
        self.teachInfoTable.verticalHeader().setDefaultSectionSize(40)
        self.teachInfoTable.verticalHeader().setMinimumSectionSize(30)
        self.gridLayout.addWidget(self.teachInfoTable, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.teachInfoPage)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.teachInfoPage, "")
        self.timeTablePage = QtWidgets.QWidget()
        self.timeTablePage.setObjectName("timeTablePage")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.timeTablePage)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.timeTable = QtWidgets.QTableWidget(self.timeTablePage)
        self.timeTable.setRowCount(12)
        self.timeTable.setColumnCount(7)
        self.timeTable.setObjectName("timeTable")
        item = QtWidgets.QTableWidgetItem()
        self.timeTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.timeTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.timeTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.timeTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.timeTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.timeTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.timeTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.timeTable.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.timeTable.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.timeTable.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.timeTable.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.timeTable.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.timeTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.timeTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.timeTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.timeTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.timeTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.timeTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.timeTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.timeTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.timeTable.setItem(0, 1, item)
        self.timeTable.horizontalHeader().setDefaultSectionSize(100)
        self.timeTable.horizontalHeader().setMinimumSectionSize(30)
        self.timeTable.verticalHeader().setDefaultSectionSize(40)
        self.gridLayout_3.addWidget(self.timeTable, 0, 0, 1, 1)
        self.tabWidget.addTab(self.timeTablePage, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 830, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionLogin = QtWidgets.QAction(MainWindow)
        self.actionLogin.setObjectName("actionLogin")
        self.actionRegister = QtWidgets.QAction(MainWindow)
        self.actionRegister.setObjectName("actionRegister")
        self.menuFile.addAction(self.actionLogin)
        self.menuFile.addAction(self.actionExit)
        self.menuAbout.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "教务选课系统-教师界面"))
        self.buttonRefresh.setText(_translate("MainWindow", "刷新"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mainPage), _translate("MainWindow", "主页"))
        item = self.teachInfoTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.teachInfoTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.teachInfoTable.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.teachInfoTable.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.teachInfoTable.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.teachInfoTable.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.teachInfoTable.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.teachInfoTable.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.teachInfoTable.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "10"))
        item = self.teachInfoTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "课程号"))
        item = self.teachInfoTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "课程名"))
        item = self.teachInfoTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "时间"))
        item = self.teachInfoTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "地点"))
        self.pushButton_2.setText(_translate("MainWindow", "刷新"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.teachInfoPage), _translate("MainWindow", "授课信息"))
        item = self.timeTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "8:30-9:15"))
        item = self.timeTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "9:25-10:10"))
        item = self.timeTable.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "10:30-11:15"))
        item = self.timeTable.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "11:25-12:10"))
        item = self.timeTable.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "14:00-14:45"))
        item = self.timeTable.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "14:55-15:40"))
        item = self.timeTable.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "15:50-16:35"))
        item = self.timeTable.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "16:45-17:30"))
        item = self.timeTable.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "18:30-19:15"))
        item = self.timeTable.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "19:25-20:10"))
        item = self.timeTable.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "20:20-21:05"))
        item = self.timeTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "MON"))
        item = self.timeTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "TUE"))
        item = self.timeTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "WED"))
        item = self.timeTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "THU"))
        item = self.timeTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "FRI"))
        item = self.timeTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "SAT"))
        item = self.timeTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "SUN"))
        __sortingEnabled = self.timeTable.isSortingEnabled()
        self.timeTable.setSortingEnabled(False)
        self.timeTable.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.timeTablePage), _translate("MainWindow", "时间表"))
        self.menuFile.setTitle(_translate("MainWindow", "操作"))
        self.menuAbout.setTitle(_translate("MainWindow", "关于"))
        self.actionExit.setText(_translate("MainWindow", "退出"))
        self.actionAbout.setText(_translate("MainWindow", "关于"))
        self.actionLogin.setText(_translate("MainWindow", "登录"))
        self.actionRegister.setText(_translate("MainWindow", "注册"))
